version: '3.7'

services:
  golem.api:
    build:
      context: .
      dockerfile: Golem.Api/Dockerfile

  bookclub.client:
    build:
      context: .
      dockerfile: Golem-Client/Dockerfile
    ports:
      - "8888:80"
